<?php

function lab_generic_analysis_configs(): array
{
    return [
        'suelos-ph' => [
            'key' => 'suelos.ph',
            'tipo' => 'Suelos',
            'elemento' => 'pH',
            'table' => 'suelo_ph',
            'tipos' => ['suelos', 'suelo'],
            'analisis' => ['pH'],
            'fields' => [
                ['name' => 'ph', 'label' => 'pH'],
                ['name' => 'temperatura', 'label' => 'Temperatura'],
            ],
        ],
        'suelos-cic' => [
            'key' => 'suelos.cic',
            'tipo' => 'Suelos',
            'elemento' => 'CIC',
            'table' => 'suelo_macros',
            'tipos' => ['suelos', 'suelo'],
            'analisis' => ['CIC', 'capacidad de intercambio cationico', 'capacidad de intercambio catiónico'],
            'fields' => [
                ['name' => 'cic_blanco', 'label' => 'CIC blanco'],
                ['name' => 'cic_muestra', 'label' => 'CIC muestra'],
                ['name' => 'cic_meq', 'label' => 'CIC meq'],
                ['name' => 'control', 'label' => 'Control'],
            ],
        ],
        'suelos-mo' => [
            'key' => 'suelos.mo',
            'tipo' => 'Suelos',
            'elemento' => '%MO',
            'table' => 'MO_Porcentaje',
            'tipos' => ['suelos', 'suelo'],
            'analisis' => ['Materia organica', 'Materia orgánica', '%MO'],
            'fields' => [
                ['name' => 'peso_muestra', 'label' => 'Peso muestra'],
                ['name' => 'sulfato_ferroso_consumido', 'label' => 'Sulfato ferroso consumido'],
                ['name' => 'porcentaje_carbono_organico', 'label' => '% carbono orgánico'],
                ['name' => 'porcentaje_materia_organica', 'label' => '% materia orgánica'],
                ['name' => 'm1_dicromato', 'label' => 'M1 dicromato'],
                ['name' => 'm2_dicromato', 'label' => 'M2 dicromato'],
                ['name' => 'val_solucion_ferroso', 'label' => 'Val. solución ferroso'],
                ['name' => 'normalidad_sulfato_ferroso', 'label' => 'Normalidad sulfato ferroso'],
                ['name' => 'ml_util_sulfato_ferroso1N', 'label' => 'ml útil sulfato ferroso 1N'],
                ['name' => 'dicromato_potasio', 'label' => 'Dicromato potasio'],
                ['name' => 'dicromato_consumido', 'label' => 'Dicromato consumido'],
                ['name' => 'blanco_sulfato_ferroso', 'label' => 'Blanco sulfato ferroso'],
                ['name' => 'blanco_sulfato_ferroso_2', 'label' => 'Blanco sulfato ferroso 2'],
            ],
        ],
        'suelos-textura' => [
            'key' => 'suelos.textura',
            'tipo' => 'Suelos',
            'elemento' => 'Textura',
            'table' => 'analisis_textura',
            'tipos' => ['suelos', 'suelo'],
            'analisis' => ['Textura'],
            'fields' => [
                ['name' => 'porcentaje_hr', 'label' => '% HR'],
                ['name' => 'lectura_1', 'label' => 'Lectura 1'],
                ['name' => 'temp_1', 'label' => 'Temp. 1'],
                ['name' => 'lectura_corregida_1', 'label' => 'Lectura corregida 1'],
                ['name' => 'porcentaje_l_a', 'label' => '% L+A'],
                ['name' => 'lectura_2', 'label' => 'Lectura 2'],
                ['name' => 'temp_2', 'label' => 'Temp. 2'],
                ['name' => 'lectura_corregida_2', 'label' => 'Lectura corregida 2'],
                ['name' => 'total', 'label' => 'Total'],
                ['name' => 'porcentaje_arcilla', 'label' => '% arcilla'],
                ['name' => 'porcentaje_limo', 'label' => '% limo'],
                ['name' => 'porcentaje_arena', 'label' => '% arena'],
                ['name' => 'textura', 'label' => 'Textura', 'type' => 'text'],
            ],
        ],
        'suelos-humedad' => [
            'key' => 'suelos.humedad',
            'tipo' => 'Suelos',
            'elemento' => 'Humedad',
            'table' => 'suelo_humedad',
            'tipos' => ['suelos', 'suelo'],
            'analisis' => ['Humedad', 'Humedad gravimetrica', 'Humedad gravimétrica'],
            'fields' => [
                ['name' => 'humedad', 'label' => 'Humedad'],
            ],
        ],
        'suelos-dap' => [
            'key' => 'suelos.dap',
            'tipo' => 'Suelos',
            'elemento' => 'DAP',
            'table' => 'suelo_dap',
            'tipos' => ['suelos', 'suelo'],
            'analisis' => ['Densidad aparente', 'DAP'],
            'fields' => [
                ['name' => 'peso_caja', 'label' => 'Peso caja'],
                ['name' => 'peso_muestra_seca', 'label' => 'Peso muestra seca'],
                ['name' => 'volumen_final', 'label' => 'Volumen final'],
                ['name' => 'peso_suelo_seco', 'label' => 'Peso suelo seco'],
                ['name' => 'densidad', 'label' => 'Densidad'],
            ],
        ],
        'suelos-humedad-residual' => [
            'key' => 'suelos.humedad_residual',
            'tipo' => 'Suelos',
            'elemento' => 'Humedad residual',
            'table' => 'laboratorio_humedad',
            'tipos' => ['suelos', 'suelo'],
            'analisis' => ['Humedad residual'],
            'fields' => [
                ['name' => 'NoCaja', 'label' => 'No. caja'],
                ['name' => 'PesoCaja', 'label' => 'Peso caja'],
                ['name' => 'PesoCajaMHumeda', 'label' => 'Peso caja + muestra húmeda'],
                ['name' => 'PesoCajaMseca', 'label' => 'Peso caja + muestra seca'],
                ['name' => 'PesoSeco', 'label' => 'Peso seco'],
                ['name' => 'PesoHumedo', 'label' => 'Peso húmedo'],
                ['name' => 'PorHGrav', 'label' => '% H grav.'],
            ],
        ],
        'aguas-macros' => [
            'key' => 'aguas.macros',
            'tipo' => 'Aguas',
            'elemento' => 'Macros',
            'table' => 'agua_macros',
            'tipos' => ['agua', 'aguas'],
            'analisis' => ['Macros', 'Macronutrientes'],
            'fields' => [
                ['name' => 'ca_ml', 'label' => 'Ca ug/ml'],
                ['name' => 'mg_ml', 'label' => 'Mg ug/ml'],
                ['name' => 'k_ml', 'label' => 'K ug/ml'],
                ['name' => 'na_ml', 'label' => 'Na ug/ml'],
                ['name' => 'blanco_ca', 'label' => 'Blanco Ca'],
                ['name' => 'blanco_mg', 'label' => 'Blanco Mg'],
                ['name' => 'blanco_k', 'label' => 'Blanco K'],
                ['name' => 'blanco_na', 'label' => 'Blanco Na'],
            ],
        ],
        'aguas-ras' => [
            'key' => 'aguas.ras',
            'tipo' => 'Aguas',
            'elemento' => 'RAS',
            'table' => 'agua_ras',
            'tipos' => ['agua', 'aguas'],
            'analisis' => ['RAS'],
            'fields' => [
                ['name' => 'na_ug', 'label' => 'Na ug'],
                ['name' => 'ca_ug', 'label' => 'Ca ug'],
                ['name' => 'mg_ug', 'label' => 'Mg ug'],
            ],
        ],
        'aguas-micros' => [
            'key' => 'aguas.micros',
            'tipo' => 'Aguas',
            'elemento' => 'Micro Nutrientes',
            'table' => 'agua_micros',
            'tipos' => ['agua', 'aguas'],
            'analisis' => ['Micro Nutrientes', 'Micronutrientes', 'Cu, Zn, Fe, Mn'],
            'fields' => [
                ['name' => 'conc_cu', 'label' => 'Cu ug/ml'],
                ['name' => 'conc_zn', 'label' => 'Zn ug/ml'],
                ['name' => 'conc_fe', 'label' => 'Fe ug/ml'],
                ['name' => 'conc_mn', 'label' => 'Mn ug/ml'],
                ['name' => 'blk_cu', 'label' => 'Blanco Cu'],
                ['name' => 'blk_zn', 'label' => 'Blanco Zn'],
                ['name' => 'blk_fe', 'label' => 'Blanco Fe'],
                ['name' => 'blk_mn', 'label' => 'Blanco Mn'],
            ],
        ],
        'aguas-boro' => [
            'key' => 'aguas.boro',
            'tipo' => 'Aguas',
            'elemento' => 'Boro',
            'table' => 'agua_boro',
            'tipos' => ['agua', 'aguas'],
            'analisis' => ['Boro'],
            'fields' => [
                ['name' => 'abs_blanco', 'label' => 'Abs. blanco'],
                ['name' => 'absorbancia', 'label' => 'Absorbancia'],
                ['name' => 'pendiente', 'label' => 'Pendiente'],
                ['name' => 'intercepto', 'label' => 'Intercepto'],
                
            ],
        ],
        'aguas-ph' => [
            'key' => 'aguas.ph',
            'tipo' => 'Aguas',
            'elemento' => 'pH',
            'table' => 'agua_ph',
            'tipos' => ['agua', 'aguas'],
            'analisis' => ['pH'],
            'fields' => [
                ['name' => 'ph', 'label' => 'pH'],
            ],
        ],
        'aguas-salinidad' => [
            'key' => 'aguas.salinidad',
            'tipo' => 'Aguas',
            'elemento' => 'Salinidad',
            'table' => 'agua_salinidad',
            'tipos' => ['agua', 'aguas'],
            'analisis' => ['Salinidad'],
            'fields' => [
                ['name' => 'lectura_psu', 'label' => 'Lectura PSU'],
            ],
        ],
        'aguas-dureza' => [
            'key' => 'aguas.dureza',
            'tipo' => 'Aguas',
            'elemento' => 'Dureza',
            'table' => 'agua_dureza',
            'tipos' => ['agua', 'aguas'],
            'analisis' => ['Dureza', 'Dureza total'],
            'fields' => [
                ['name' => 'ml_edta', 'label' => 'ml EDTA'],
                ['name' => 'ml_muestra', 'label' => 'ml muestra'],
            ],
        ],
        'aguas-carbonatos' => [
            'key' => 'aguas.carbonatos',
            'tipo' => 'Aguas',
            'elemento' => 'Carbonatos',
            'table' => 'agua_carbonatos',
            'tipos' => ['agua', 'aguas'],
            'analisis' => ['Carbonatos'],
            'fields' => [
                ['name' => 'ml_h2so4', 'label' => 'ml H2SO4'],
                ['name' => 'normalidad_h2so4', 'label' => 'Normalidad H2SO4'],
                ['name' => 'volumen_muestra', 'label' => 'Volumen muestra'],
            ],
        ],
        'foliares-macros' => [
            'key' => 'foliares.macros',
            'tipo' => 'Foliares',
            'elemento' => 'Macros',
            'table' => 'foliar_macros',
            'tipos' => ['foliares', 'foliar'],
            'analisis' => ['Macros', 'Macronutrientes'],
            'fields' => [
                ['name' => 'calcio', 'label' => 'Calcio'],
                ['name' => 'magnesio', 'label' => 'Magnesio'],
                ['name' => 'potasio', 'label' => 'Potasio'],
            ],
        ],
        'foliares-nitrogeno' => [
            'key' => 'foliares.nitrogeno',
            'tipo' => 'Foliares',
            'elemento' => 'Nitrógeno',
            'table' => 'foliar_nitrogeno',
            'tipos' => ['foliares', 'foliar'],
            'analisis' => ['Nitrogeno', 'Nitrógeno'],
            'fields' => [
                ['name' => 'ml_gastado', 'label' => 'ml gastado'],
                ['name' => 'normalidad', 'label' => 'Normalidad'],
                ['name' => 'resultado', 'label' => 'Resultado'],
            ],
        ],
        'foliares-boro' => [
            'key' => 'foliares.boro',
            'tipo' => 'Foliares',
            'elemento' => 'Boro',
            'table' => 'foliar_boro',
            'tipos' => ['foliares', 'foliar'],
            'analisis' => ['Boro'],
            'fields' => [
                ['name' => 'absorbancia', 'label' => 'Absorbancia'],
                ['name' => 'resultado', 'label' => 'Resultado'],
            ],
        ],
        'cana-peso-seco' => [
            'key' => 'cana.peso_seco',
            'tipo' => 'Caña',
            'elemento' => 'Peso seco',
            'table' => 'cana_peso_seco',
            'tipos' => ['cañas', 'caña', 'canas', 'cana'],
            'analisis' => ['Peso seco'],
            'fields' => [
                ['name' => 'num_bandeja', 'label' => 'No. bandeja'],
                ['name' => 'peso_bandeja', 'label' => 'Peso bandeja'],
                ['name' => 'peso_muestra', 'label' => 'Peso muestra'],
                ['name' => 'bandeja_humeda', 'label' => 'Bandeja húmeda'],
                ['name' => 'bandeja_seca', 'label' => 'Bandeja seca'],
                ['name' => 'torta_seca', 'label' => 'Torta seca'],
            ],
        ],
        'cana-fibra' => [
            'key' => 'cana.fibra',
            'tipo' => 'Caña',
            'elemento' => 'Fibra',
            'table' => 'cana_fibra',
            'tipos' => ['cañas', 'caña', 'canas', 'cana'],
            'analisis' => ['Fibra', 'Fibra bruta'],
            'fields' => [
                ['name' => 'vd', 'label' => 'VD', 'type' => 'text'],
                ['name' => 'brix_jugo', 'label' => 'Brix jugo'],
                ['name' => 'torta_humeda', 'label' => 'Torta húmeda'],
                ['name' => 'torta_seca', 'label' => 'Torta seca'],
                ['name' => 'fibra', 'label' => 'Fibra'],
            ],
        ],
        'mieles-brix' => [
            'key' => 'mieles.brix',
            'tipo' => 'Mieles',
            'elemento' => 'Brix',
            'table' => 'mieles_brix',
            'tipos' => ['mieles', 'miel'],
            'analisis' => ['Brix'],
            'fields' => [
                ['name' => 'producto', 'label' => 'Producto', 'type' => 'text'],
                ['name' => 'ingenio', 'label' => 'Ingenio', 'type' => 'text'],
                ['name' => 'dia_zafra', 'label' => 'Dia zafra', 'type' => 'text'],
                ['name' => 'brix_obs', 'label' => 'Brix obs.'],
                ['name' => 'brix_corr', 'label' => 'Brix corr.'],
            ],
        ],
    ];
}

function lab_generic_analysis_config(string $slug): ?array
{
    $configs = lab_generic_analysis_configs();
    return $configs[$slug] ?? null;
}
