<?php

function lab_generic_analysis_configs(): array
{
    return [
        'aguas-macros' => [
            'key' => 'aguas.macros',
            'tipo' => 'Aguas',
            'elemento' => 'Macros',
            'table' => 'agua_macros',
            'tipos' => ['agua', 'aguas'],
            'analisis' => ['Macros', 'Macronutrientes'],
            'fields' => [
                ['name' => 'factor_dilucion', 'label' => 'Factor dilucion'],
                ['name' => 'ca_ml', 'label' => 'Ca ml'],
                ['name' => 'mg_ml', 'label' => 'Mg ml'],
                ['name' => 'k_ml', 'label' => 'K ml'],
                ['name' => 'na_ml', 'label' => 'Na ml'],
                ['name' => 'blanco_ca', 'label' => 'Blanco Ca'],
                ['name' => 'blanco_mg', 'label' => 'Blanco Mg'],
                ['name' => 'blanco_k', 'label' => 'Blanco K'],
                ['name' => 'blanco_na', 'label' => 'Blanco Na'],
                ['name' => 'ca_mgl', 'label' => 'Ca mg/L'],
                ['name' => 'mg_mgl', 'label' => 'Mg mg/L'],
                ['name' => 'k_mgl', 'label' => 'K mg/L'],
                ['name' => 'na_mgl', 'label' => 'Na mg/L'],
            ],
        ],
        'aguas-ras' => [
            'key' => 'aguas.ras',
            'tipo' => 'Aguas',
            'elemento' => 'RAS',
            'table' => 'agua_ras',
            'tipos' => ['agua', 'aguas'],
            'analisis' => ['RAS'],
            'fields' => [
                ['name' => 'na_ug', 'label' => 'Na ug'],
                ['name' => 'ca_ug', 'label' => 'Ca ug'],
                ['name' => 'mg_ug', 'label' => 'Mg ug'],
                ['name' => 'na_meq', 'label' => 'Na meq'],
                ['name' => 'ca_meq', 'label' => 'Ca meq'],
                ['name' => 'mg_meq', 'label' => 'Mg meq'],
                ['name' => 'ras', 'label' => 'RAS'],
            ],
        ],
        'aguas-boro' => [
            'key' => 'aguas.boro',
            'tipo' => 'Aguas',
            'elemento' => 'Boro',
            'table' => 'agua_boro',
            'tipos' => ['agua', 'aguas'],
            'analisis' => ['Boro'],
            'fields' => [
                ['name' => 'abs_blanco', 'label' => 'Abs. blanco'],
                ['name' => 'absorbancia', 'label' => 'Absorbancia'],
                ['name' => 'pendiente', 'label' => 'Pendiente'],
                ['name' => 'intercepto', 'label' => 'Intercepto'],
                ['name' => 'boro', 'label' => 'Boro'],
            ],
        ],
        'aguas-ph' => [
            'key' => 'aguas.ph',
            'tipo' => 'Aguas',
            'elemento' => 'pH',
            'table' => 'agua_ph',
            'tipos' => ['agua', 'aguas'],
            'analisis' => ['pH'],
            'fields' => [
                ['name' => 'ph', 'label' => 'pH'],
            ],
        ],
        'aguas-salinidad' => [
            'key' => 'aguas.salinidad',
            'tipo' => 'Aguas',
            'elemento' => 'Salinidad',
            'table' => 'agua_salinidad',
            'tipos' => ['agua', 'aguas'],
            'analisis' => ['Salinidad'],
            'fields' => [
                ['name' => 'lectura_psu', 'label' => 'Lectura PSU'],
            ],
        ],
        'aguas-dureza' => [
            'key' => 'aguas.dureza',
            'tipo' => 'Aguas',
            'elemento' => 'Dureza',
            'table' => 'agua_dureza',
            'tipos' => ['agua', 'aguas'],
            'analisis' => ['Dureza', 'Dureza total'],
            'fields' => [
                ['name' => 'ml_edta', 'label' => 'ml EDTA'],
                ['name' => 'ml_muestra', 'label' => 'ml muestra'],
                ['name' => 'dureza', 'label' => 'Dureza'],
            ],
        ],
        'aguas-carbonatos' => [
            'key' => 'aguas.carbonatos',
            'tipo' => 'Aguas',
            'elemento' => 'Carbonatos',
            'table' => 'agua_carbonatos',
            'tipos' => ['agua', 'aguas'],
            'analisis' => ['Carbonatos'],
            'fields' => [
                ['name' => 'ml_h2so4', 'label' => 'ml H2SO4'],
                ['name' => 'normalidad_h2so4', 'label' => 'Normalidad H2SO4'],
                ['name' => 'volumen_muestra', 'label' => 'Volumen muestra'],
                ['name' => 'carbonatos', 'label' => 'Carbonatos'],
            ],
        ],
        'foliares-macros' => [
            'key' => 'foliares.macros',
            'tipo' => 'Foliares',
            'elemento' => 'Macros',
            'table' => 'foliar_macros',
            'tipos' => ['foliares', 'foliar'],
            'analisis' => ['Macros', 'Macronutrientes'],
            'fields' => [
                ['name' => 'calcio', 'label' => 'Calcio'],
                ['name' => 'magnesio', 'label' => 'Magnesio'],
                ['name' => 'potasio', 'label' => 'Potasio'],
            ],
        ],
        'foliares-nitrogeno' => [
            'key' => 'foliares.nitrogeno',
            'tipo' => 'Foliares',
            'elemento' => 'Nitrogeno',
            'table' => 'foliar_nitrogeno',
            'tipos' => ['foliares', 'foliar'],
            'analisis' => ['Nitrogeno', 'Nitrogeno'],
            'fields' => [
                ['name' => 'ml_gastado', 'label' => 'ml gastado'],
                ['name' => 'normalidad', 'label' => 'Normalidad'],
                ['name' => 'resultado', 'label' => 'Resultado'],
            ],
        ],
        'foliares-boro' => [
            'key' => 'foliares.boro',
            'tipo' => 'Foliares',
            'elemento' => 'Boro',
            'table' => 'foliar_boro',
            'tipos' => ['foliares', 'foliar'],
            'analisis' => ['Boro'],
            'fields' => [
                ['name' => 'absorbancia', 'label' => 'Absorbancia'],
                ['name' => 'resultado', 'label' => 'Resultado'],
            ],
        ],
        'cana-peso-seco' => [
            'key' => 'cana.peso_seco',
            'tipo' => 'Cana',
            'elemento' => 'Peso seco',
            'table' => 'cana_peso_seco',
            'tipos' => ['canas', 'cana', 'canas', 'cana'],
            'analisis' => ['Peso seco'],
            'fields' => [
                ['name' => 'num_bandeja', 'label' => 'No. bandeja'],
                ['name' => 'peso_bandeja', 'label' => 'Peso bandeja'],
                ['name' => 'peso_muestra', 'label' => 'Peso muestra'],
                ['name' => 'bandeja_humeda', 'label' => 'Bandeja humeda'],
                ['name' => 'bandeja_seca', 'label' => 'Bandeja seca'],
                ['name' => 'torta_seca', 'label' => 'Torta seca'],
            ],
        ],
        'cana-fibra' => [
            'key' => 'cana.fibra',
            'tipo' => 'Cana',
            'elemento' => 'Fibra',
            'table' => 'cana_fibra',
            'tipos' => ['canas', 'cana', 'canas', 'cana'],
            'analisis' => ['Fibra', 'Fibra bruta'],
            'fields' => [
                ['name' => 'vd', 'label' => 'VD', 'type' => 'text'],
                ['name' => 'brix_jugo', 'label' => 'Brix jugo'],
                ['name' => 'torta_humeda', 'label' => 'Torta humeda'],
                ['name' => 'torta_seca', 'label' => 'Torta seca'],
                ['name' => 'fibra', 'label' => 'Fibra'],
            ],
        ],
        'mieles-brix' => [
            'key' => 'mieles.brix',
            'tipo' => 'Mieles',
            'elemento' => 'Brix',
            'table' => 'mieles_brix',
            'tipos' => ['mieles', 'miel'],
            'analisis' => ['Brix'],
            'fields' => [
                ['name' => 'producto', 'label' => 'Producto', 'type' => 'text'],
                ['name' => 'ingenio', 'label' => 'Ingenio', 'type' => 'text'],
                ['name' => 'dia_zafra', 'label' => 'Dia zafra', 'type' => 'text'],
                ['name' => 'brix_obs', 'label' => 'Brix obs.'],
                ['name' => 'brix_corr', 'label' => 'Brix corr.'],
            ],
        ],
    ];
}

function lab_generic_analysis_config(string $slug): ?array
{
    $configs = lab_generic_analysis_configs();
    return $configs[$slug] ?? null;
}
